/*
 * SudukuHeader.h
 *
 *  Created on: 1 gru 2013
 *      Author: Baraka
 */

#ifndef SUDUKUHEADER_H_
#define SUDUKUHEADER_H_

#include "datastructue.h"

//given a grid, replace all cell contents with VALUE
//EMPTY_VALUE means blank cell, digit stand for[1,9]
void loadGame (sudukoGame game);//side effect
//display sudoko grid in format to read
void showGame (sudukoGame game);//side effect

//sets a free cell in sudoko
//assume cell and digit are in legal range
void setFreeCell(sudukoGame game,cell candidateCell,value initialValue);
//return the location of a blank cell
//assume that exists blank cell
cell getFreeCell (sudukoGame game);
//sets the specific cell to be blank
//assumes cell location is in legal range
void clearCell (sudukoGame game,cell candidateCell);
//return true if is full grid and else false
bool isFull (sudukoGame game);
//return true iff it would be legal to set the special digit
//assume cell location and digit are in legal range
//and current game has been generated by a sequence
bool isLegal (sudukoGame game,cell candidateCell,value initialValue);
// returns most common digit in the grid
//if two+ are equally common return either+
//(so, if all empty return any)
value mostCommonValue (sudukoGame game);

#endif /* SUDUKUHEADER_H_ */
